site_name: ASTi CO - Docs
site_description: Documentazione ASTi
# site_url :
# Repository
# repo_name: asti-co/doc
repo_name: ""
repo_url: https://github.com/asti-co/doc
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  icon:
    # .svg automatically appended
    # logo: material/library
  logo: img/asti_small.gif
  features:
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  # - toc.integrate

  palette:
    - scheme: default
      primary: red
      accent: indigo
      toggle: 
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: blue
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  language: it

nav:
  - Home: index.md
  - Gestione gara - concorrenti:
      - "gestione_gara_conc/index.md"
      - Pre-gara:
          - "gestione_gara_conc/pregara/index.md"
          - Informazioni: gestione_gara_conc/pregara/informazioni.md
          - Iscrizioni: gestione_gara_conc/pregara/iscrizioni.md
      - Gara:
          - "gestione_gara_conc/gara/index.md"
          - SIAC: gestione_gara_conc/gara/siac.md
          - Partecipazione alla gara: gestione_gara_conc/gara/partecipazione_gara.md
      - Post-gara:
          - "gestione_gara_conc/postgara/index.md"
          - Classifiche: gestione_gara_conc/postgara/classifiche_conc.md
          - RouteGadget: gestione_gara_conc/postgara/routegadget_conc.md
  - Gestione gara - organizzatori:
      - "gestione_gara_org/index.md"
      - TMO / Nazionali: gestione_gara_org/tmo_nazionali.md
      - Staffetta Sele: gestione_gara_org/staffetta_sele.md     
      - sCOOLcup: gestione_gara_org/scool_cup.md     
  - Materiale:
      - "materiale/index.md"
      - Scatola gialla: materiale/materiale_informatico.md
      - Router: materiale/router.md
      - Rete: materiale/rete.md
      - Punti radio: materiale/punti_radio.md
      - Ponti radio: materiale/ponti_radio.md
      - TV: materiale/tv.md
      - SPORTident:
          - "materiale/sportident/index.md"
          - Panoramica: "materiale/sportident/panoramica.md"
          - Punti: "materiale/sportident/scatolette.md"
          - Sincronizzazione Punti: materiale/sportident/sincronizzazione_punti.md
          - Chip: "materiale/sportident/chip.md"
          - Paletti: "materiale/sportident/paletti.md"
          - Punti Radio: "materiale/sportident/punti_radio.md"
  - Software:
      - "software/index.md"
      - OE 12:
          - "software/oe12/index.md"
          - Panoramica: software/oe12/panoramica.md
          - Interfaccia grafica: software/oe12/interfaccia_grafica.md
          - Creazione gara: software/oe12/creazione_gara.md
          - Iscrizioni tardive: software/oe12/iscrizioni_tardive.md
          - Liste di partenza: software/oe12/liste_partenza.md
          - Varie pre-gara: software/oe12/varie_pre_gara.md
          - Mutazioni: software/oe12/mutazioni_giorno_gara.md
          - Lettura Chip: software/oe12/lettura_chip.md
          - Casi Normali: software/oe12/casi_normali.md
          - Casi Speciali: software/oe12/casi_speciali.md
          - Classifiche: software/oe12/classifiche.md
          - Gestione Finanziaria: software/oe12/finanze.md
          - Archivio: software/oe12/archivio.md
          - Punti radio SPORTident: software/oe12/punti_radio.md
      - Portali Iscrizioni: 
          - "software/portali_iscrizioni/index.md"
          - OL-Events: 
              - "software/portali_iscrizioni/olevents/index.md"
              - Creazione gara: software/portali_iscrizioni/olevents/organizzatori.md
              - Iscrizioni: software/portali_iscrizioni/olevents/concorrenti.md
      - OCAD:
          - Per tracciatori: "software/ocad/ocad_tracciatore.md"
      - O2rank:
          - "software/o2rank/index.md"
          - Creazione gara: software/o2rank/creazione_gara.md
          - Punti radio: software/o2rank/punti_radio.md
          - Visualizzazione: software/o2rank/concorrenti.md
      - SOLV DB:
          - Registrazione concorrente: software/solvDB/solvDB.md
          - Mutazione concorrente: software/solvDB/solvDB.md
  - Sito ASTI:
      - "sito_asti/index.md"
      - Classifiche TMO: sito_asti/classifiche_tmo.md
      - Classifiche Sprintup: sito_asti/classifiche_sprintcup.md
      - RouteGadget: sito_asti/routegadget.md
  - About:
      - "about/index.md"
      - Documentazione: about/documentazione.md
      - Tooling: about/tooling.md
      - Cambiamenti: about/cambiamenti.md

# Plugins
plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

